image: openjdk:8-jdk
#https://medium.com/faun/gitlab-ci-cd-configuring-gitlab-ci-yml-file-for-react-native-android-8fe7612a516

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - apt-get install -y sudo #to prevent: /bin/bash: line 127: sudo: command not found
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x android/gradlew #Provide permission for execution
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

  - curl -sL https://deb.nodesource.com/setup_10.x | bash #Add Node Repo
  - apt-get install -y nodejs #Install NOde JS
  - npm install #Install npm packages
  - npm install -g react-native-cli #Install React-Native CLI
  - react-native link #Link the resources

  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p #https://github.com/gatsbyjs/gatsby/issues/11406
#  - cat /proc/sys/fs/inotify/max_user_watches
#  - fs.inotify.max_user_watches=524288


stages:
  - build
  - test
  - release

android:release-build:
  stage: build
  script:
    - npm run release-android
  artifacts:
    paths:
    - android/app/build/outputs/

test:
  stage: test
  script:
    - npm run test

gitlab-release:
  stage: release
  only:
    - master
  variables:
    GITLAB_TOKEN: $CI_ACCESS_TOKEN
  script:
    - npm install -g semantic-release @semantic-release/{gitlab,git,changelog}
    #- cat $SEMVER_RELEASE_OPTIONS > .releaserc.json
    - semantic-release
  artifacts:
    paths:
    - android/app/build/outputs/
  