const STORAGE_KEYS = {
  IS_NO_ADS_PURCHASED: 'IS_NO_ADS_PURCHASED',

  // RATING
  RATE_US_DATE_SHOWN: 'RATE_US_DATE_SHOWN',
  RATE_US_APP_RATED: 'RATE_US_APP_RATED',
  RUNS_COUNT_TODAY: 'RUNS_COUNT_TODAY',
  RATE_US_NOTNOW_PRESSED: 'RATE_US_NOTNOW_PRESSED',

  PRESSED_SMA_BUTTONS: 'PRESSED_SMA_BUTTONS',
};

export default STORAGE_KEYS;
